### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by prayerslayer** [zalando-incubator/react-automatic-width#11]
I'm stepping down as a maintainer of this project, anyone want to pick it up? It's very low effort: Feature-complete, no dependencies and no complaining users.

**Comment by rubenspgcavalcante** [comment]
Sure, can be me. 👍

**Comment by prayerslayer** [comment]
Cool! Would you mind creating a PR with your name in the MAINTAINERS file to make it official?
